### ISSUE TITLE
Forcing to remove new line from the text

### ISSUE THREAD

**Issue by verhas** [markuadoc/markua#22]
The reasoning in the documentation:

"The idea is that most modern text editors automatically wrap lines, so
there's no need to add a newline unless you're explicitly trying to create
a newline -- like, say, in poetry."

Is wrong. The new lines in the source code of the document are to help the maintenance of the document.

For example, the asciidoc recommended practice:

https://asciidoctor.org/docs/asciidoc-recommended-practices/

cannot be followed using Markua, or even worse: I need a preprocessor that converts my markdown technical book to Markua.

**Comment by MattiasMartens** [comment]
Hi, I came here to say the same thing. To narrow down the citation of @verhas, the best practice in question is here: https://asciidoctor.org/docs/asciidoc-recommended-practices#one-sentence-per-line

Reasons given for the practice:

- It prevents reflows (meaning a change early in the paragraph won’t cause the remaining lines in the paragraph to reposition).
- You can easily swap sentences.
- You can easily separate or join paragraphs.
- You can comment out sentences or add commentary to them.
- You can spot sentences which are too long or sentences that vary widely in length.
- You can spot redundant (and thus mundane) patterns in your writing.

In other words, it promotes ease-of-use for writers. I'll add that if you're using version control, it is indispensable because you can change a sentence without having a whole paragraph highlighted as changed. I'm editing my book and I like seeing which sentences I've touched since my last commit.

Here's a proposal for an alternative spec:

1. A configuration option to collapse single newlines. In this regime, a newline *can* indicate a line break *if* it is immediately followed by a tilde (~), as in:

```
Sphinx of Black Quartz, Judge My Vow.
~ Wait.
~ Really?
```

(With an optional space after the tilde, ignored if present.)

It is natural for code blocks to be an exception to this, even with the configuration option set.

I like the tilde as a choice of control character here because it doesn't collide with any formatting from original Markdown and readability does not suffer for it, at least in my observation.

I know introducing configuration flags like this is a worrying path to go down, but this does strike me as a rather important one. In any case, this is just to say that I'm thinking along the same lines as @verhas and the thought of transpiling from my preferred format to the allegedly breezy Markua makes me feel kind of ill. LOL

**Comment by peterarmstrong** [comment]
Sorry for the huge delay here. This is resolved now here:
http://markua.com/#the-soft-breaks-document-setting-m-

**Comment by peterarmstrong** [comment]
(It's resolved in Markua 0.30. The spec is at markua.com. I'm writing the manual here on a branch.)
