### ISSUE TITLE
Smart quotes/apostrophes?

### ISSUE THREAD

**Issue by JacobEvelyn** [markuadoc/markua#4]
In playing around with Leanpub I noticed that it turns the characters `"` and `'` into `“`, `”`, and `’` as appropriate. However, I couldn't find anything in the Markua spec that describes this. Is that something you guys would be interested in adding?

**Comment by JacobEvelyn** [comment]
Just curious if there's any movement on this.

**Comment by peterarmstrong** [comment]
Hi Jacob,

I'm on vacation until Tuesday, and I'm trying to not look at Markua until then :)

Thanks very much for the pull requests and comments!  I will process them all next week.

Please note that I did a huge revision of the Markua spec recently, so chances are some stuff has changed since you created them.

Finally, I'd like to apologize: I missed your PRs until recently, since frankly, I wasn't looking and since this repo is on the markuadoc account and not my personal GitHub account.  I need to fix my workflow so I don't miss comments and PRs in future.

Thanks very much, by the way!

Cheers
Peter

**Comment by peterarmstrong** [comment]
Hi Jacob,

I've added a discussion of this now.

Thanks again!
Peter
